blank_issues_enabled: false
contact_links:
  - name: ORY Community Forum
    url: https://community.ory.sh/
    about: Please ask and answer questions here.
  - name: ORY Security Contact
    url: mailto:security@ory.sh
    about: Please report security vulnerabilities here.
  - name: ORY Enterprise Contact
    url: mailto:jared@ory.sh
    about: Please conatact Jared for enterprise-related inquiries.
