blank_issues_enabled: false
contact_links:
  - name: ORY Community Forum
    url: https://community.ory.sh/
    about: Please ask and answer questions here.
  - name: ORY Chat
    url: https://www.ory.sh/chat
    about: Hang out with other ORY community members and ask and answer questions.
  - name: ORY Enterprise Contact
    url: https://www.ory.sh/enterprise
    about: Please conatact Jared for enterprise-related inquiries.
